name: Buildable check
on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint:check

      - name: Check Formatting
        run: npm run format:check

      # Build the project
      - name: Build project
        run: npm run build
